### ISSUE TITLE
Union with Rosetta::Translation compile error message

### ISSUE THREAD

**Issue by albertorestifo** [wout/rosetta#10]
Having a union type with `Rosetta::Translation` results in vague error messages.

Example:

```cr
class Shared::LayoutHead < BaseComponent
  needs page_title : String | Rosetta::Translation

  def render
    head do
      utf8_charset
      title "My App - #{@page_title}"
      css_link asset("css/app.css"), data_turbolinks_track: "reload"
      css_link "https://rsms.me/inter/inter.css"
      js_link asset("js/app.js"), defer: "true", data_turbolinks_track: "reload"
      meta name: "turbolinks-cache-control", content: "no-cache"
      csrf_meta_tags
      responsive_meta_tag
    end
  end
end
```

Results in the following compile error:

```
Error: Rosetta.find("rosetta_localization.time.formats.short") expected to receive t(time : Time | Tuple(Int32, Int32, Int32)) but to_s was called instead
```

**Comment by wout** [comment]
Thanks for creating this issue. I woke up with the answer and it actually makes sense. By making the union  `String | Rosetta::Translation`, and later interpolating the value in a string (`title "My App - #{@page_title}"`, you're essentially telling Crystal that the variable `page_title` should respond to `to_s`. For all translations with interpolations that will fail to compile, and that's by design: https://github.com/wout/rosetta/blob/main/src/rosetta/parser/builder.cr#L76-L78

So this is actually a good thing. Crystal's type system is protesting for the right reasons, but Rosetta's error message is not very helpful. I've changed it to:

```
web          | In config/rosetta.cr:9:1
web          | 
web          |  9 | Rosetta::Backend.load("./config/rosetta")
web          |      ^
web          | Error: 
web          | 
web          |   Rosetta.find("avram.validate_numeric_min") expected to receive
web          |   t(size : String) but to_s was called instead.
web          | 
web          |   This error may be caused by implicitly or explicitly calling
web          |   .to_s on a Rosetta::Translation with interpolations.
web          | 
web          |   Make sure you're not using Rosetta::Translation in a string
web          |   interpolation or in a type union with String.
```

Hopefully that will help users running into the same error in the future.

**Comment by albertorestifo** [comment]
That makes a ton of sense!

Looking at the official docs in Lucky, I'm thinking that maybe it's best to avoid the examples where `.t` isn't called explicitly:

While it makes for a nice API, it can add a lot of confusion, given that like you mentioned, interpolated translations will require the `.t` call, and by teaching users to not use `.t` all the time, it might lead many to attempt the same I did, and starting to accept an union in components/other places in lucky.

What do you think?

**Comment by wout** [comment]
Yeah, that's exactly where we're moving with this :)

https://github.com/luckyframework/website/pull/1090

Not sure why it's not yet merged in the docs though, probably related to the release of Lucky version 1.0.0. But before that happens, I also want to have this PR committed:

https://github.com/luckyframework/lucky/discussions/1773
